# Generated by Django 4.0.5 on 2023-04-15 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('role', models.CharField(max_length=19, verbose_name='Роль человека')),
                ('phone', models.CharField(max_length=19, verbose_name='Номер телефона')),
                ('own_site', models.CharField(max_length=120, verbose_name='Сайт человека')),
                ('linkedin_url', models.CharField(max_length=120, verbose_name='Ссылка на Линкдин')),
                ('telegram_url', models.CharField(max_length=120, verbose_name='Ссылка на Телеграм')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
