# Generated by Django 4.0.5 on 2023-04-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_businesscard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscard',
            name='avatar',
        ),
    ]
