# Generated by Django 4.0.5 on 2023-04-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_businesscard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
