# Generated by Django 4.0.5 on 2023-04-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_businesscard_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='owner',
            field=models.IntegerField(max_length=9999, verbose_name='Айди создателя'),
        ),
    ]
