# Generated by Django 4.0.5 on 2023-04-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_businesscard_owner_businesscard_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=55, verbose_name='Айпишники вайфая')),
                ('peoples', models.TextField(verbose_name='ID людей в этой сети')),
            ],
        ),
    ]
